import type { KanbanColumn } from "./types"

export const COLUMNS: KanbanColumn[] = [
  {
    id: "backlog",
    label: "Backlog",
    color: "#94a3b8",
    tasks: [
      {
        id: "t1",
        title: "Explore onboarding flow variants",
        project: "App Redesign",
        client: "Wix",
        priority: "Medium",
        dueDate: "Apr 20",
        assignee: { initials: "HB", color: "#3b82f6" },
      },
      {
        id: "t2",
        title: "Collect references for pricing page",
        project: "Landing Page",
        client: "Zoom",
        priority: "Low",
        dueDate: "Apr 25",
        assignee: { initials: "M", color: "#ec4899" },
      },
    ],
  },
  {
    id: "todo",
    label: "To Do",
    color: "#71717a",
    tasks: [
      {
        id: "t3",
        title: "Wireframe dashboard widgets",
        project: "Dashboard UI",
        client: "Slack",
        priority: "High",
        dueDate: "Apr 8",
        assignee: { initials: "HB", color: "#3b82f6" },
      },
      {
        id: "t4",
        title: "Define empty states for feed",
        project: "Social Templates",
        client: "Meta",
        priority: "Medium",
        dueDate: "Apr 12",
        assignee: { initials: "J", color: "#10b981" },
      },
      {
        id: "t5",
        title: "Draft logo direction A",
        project: "Brand Identity",
        client: "Monday",
        priority: "High",
        dueDate: "Apr 6",
        assignee: { initials: "A", color: "#8b5cf6" },
      },
    ],
  },
  {
    id: "in-progress",
    label: "In Progress",
    color: "#3b82f6",
    tasks: [
      {
        id: "t6",
        title: "Redesign profile settings screen",
        project: "App Redesign",
        client: "Wix",
        priority: "High",
        dueDate: "Apr 10",
        assignee: { initials: "HB", color: "#3b82f6" },
      },
      {
        id: "t7",
        title: "Build email header templates",
        project: "Marketing Kit",
        client: "Fiverr",
        priority: "Medium",
        dueDate: "Apr 15",
        assignee: { initials: "M", color: "#ec4899" },
      },
    ],
  },
  {
    id: "in-review",
    label: "In Review",
    color: "#f97316",
    tasks: [
      {
        id: "t8",
        title: "Final logo presentation",
        project: "Brand Identity",
        client: "Monday",
        priority: "High",
        dueDate: "Apr 5",
        assignee: { initials: "A", color: "#8b5cf6" },
      },
      {
        id: "t9",
        title: "Analytics chart components",
        project: "Dashboard UI",
        client: "Slack",
        priority: "Medium",
        dueDate: "Apr 7",
        assignee: { initials: "HB", color: "#3b82f6" },
      },
    ],
  },
  {
    id: "approved",
    label: "Approved",
    color: "#a855f7",
    tasks: [
      {
        id: "t10",
        title: "Checkout flow hand-off pack",
        project: "App Redesign",
        client: "Wix",
        priority: "High",
        dueDate: "Apr 9",
        assignee: { initials: "HB", color: "#3b82f6" },
      },
    ],
  },
  {
    id: "in-dev",
    label: "In Dev",
    color: "#14b8a6",
    tasks: [
      {
        id: "t11",
        title: "Navigation shell components",
        project: "Dashboard UI",
        client: "Slack",
        priority: "Medium",
        dueDate: "Apr 4",
        assignee: { initials: "J", color: "#10b981" },
      },
    ],
  },
  {
    id: "done",
    label: "Done",
    color: "#10b981",
    tasks: [
      {
        id: "t12",
        title: "Icon set v2",
        project: "Marketing Kit",
        client: "Fiverr",
        priority: "Low",
        dueDate: "Mar 30",
        assignee: { initials: "M", color: "#ec4899" },
      },
      {
        id: "t13",
        title: "Color tokens audit",
        project: "Brand Identity",
        client: "Monday",
        priority: "Low",
        dueDate: "Mar 28",
        assignee: { initials: "A", color: "#8b5cf6" },
      },
    ],
  },
]
