import type { Task, TaskAssignee } from "./types"

const DANIEL: TaskAssignee = { name: "Daniel", initials: "D", color: "bg-blue-500" }
const MAYA: TaskAssignee   = { name: "Maya",   initials: "M", color: "bg-pink-500" }
const JON: TaskAssignee    = { name: "Jon",    initials: "J", color: "bg-emerald-500" }
const ADA: TaskAssignee    = { name: "Ada",    initials: "A", color: "bg-violet-500" }
const SARA: TaskAssignee   = { name: "Sara",   initials: "S", color: "bg-amber-500" }

export const TASK_ASSIGNEES: TaskAssignee[] = [DANIEL, MAYA, JON, ADA, SARA]

export const TASK_PROJECTS: string[] = [
  "App Redesign",
  "Dashboard UI",
  "Landing Page",
  "Brand Identity",
  "Marketing Kit",
  "Social Templates",
]

// Three tasks with due dates before 2026-05-29 and status ≠ Completed are overdue.
export const mockTasks: Task[] = [
  {
    id: "task-1",
    title: "Redesign profile settings screen",
    description: "Covers mobile + web. Must match the new component library.",
    status: "In Progress",
    priority: "High",
    project: "App Redesign",
    assignee: DANIEL,
    dueDate: "2026-05-20",
    createdAt: "2026-05-01",
    tags: ["UI", "Mobile"],
  },
  {
    id: "task-2",
    title: "Wireframe dashboard widgets",
    description: "Low-fidelity wireframes for all six chart widget types.",
    status: "To Do",
    priority: "High",
    project: "Dashboard UI",
    assignee: DANIEL,
    dueDate: "2026-05-22",
    createdAt: "2026-05-03",
    tags: ["Wireframe"],
  },
  {
    id: "task-3",
    title: "Analytics chart components",
    description: "Line, bar, and donut chart variants for the analytics module.",
    status: "In Review",
    priority: "Medium",
    project: "Dashboard UI",
    assignee: MAYA,
    dueDate: "2026-05-25",
    createdAt: "2026-05-05",
    tags: ["Charts"],
  },
  {
    id: "task-4",
    title: "Hero variant explorations",
    description: "At least three hero layout directions for the Zoom landing page.",
    status: "In Progress",
    priority: "High",
    project: "Landing Page",
    assignee: DANIEL,
    dueDate: "2026-05-30",
    createdAt: "2026-05-10",
    tags: ["Visual"],
  },
  {
    id: "task-5",
    title: "Pricing comparison table",
    description: "Three-tier pricing table, responsive, dark mode support.",
    status: "To Do",
    priority: "Medium",
    project: "Landing Page",
    dueDate: "2026-06-01",
    createdAt: "2026-05-10",
  },
  {
    id: "task-6",
    title: "Final logo presentation deck",
    description: "Present all three logo directions with usage guidelines.",
    status: "In Review",
    priority: "High",
    project: "Brand Identity",
    assignee: ADA,
    dueDate: "2026-06-03",
    createdAt: "2026-05-12",
    tags: ["Branding"],
  },
  {
    id: "task-7",
    title: "Color tokens audit",
    description: "Audit all brand color tokens and flag inconsistencies.",
    status: "Completed",
    priority: "Low",
    project: "Brand Identity",
    assignee: ADA,
    dueDate: "2026-05-27",
    createdAt: "2026-05-15",
  },
  {
    id: "task-8",
    title: "Build email header templates",
    description: "HTML email headers in three size variants with logo lockups.",
    status: "In Progress",
    priority: "Medium",
    project: "Marketing Kit",
    assignee: MAYA,
    dueDate: "2026-06-05",
    createdAt: "2026-05-14",
    tags: ["Email"],
  },
  {
    id: "task-9",
    title: "Story templates v2",
    description: "Updated Instagram story templates with the new brand palette.",
    status: "To Do",
    priority: "Medium",
    project: "Marketing Kit",
    assignee: ADA,
    dueDate: "2026-06-07",
    createdAt: "2026-05-14",
  },
  {
    id: "task-10",
    title: "Define empty states for feed",
    description: "Design zero-data and error states for the social feed grid.",
    status: "To Do",
    priority: "Medium",
    project: "Social Templates",
    assignee: JON,
    dueDate: "2026-06-10",
    createdAt: "2026-05-16",
    tags: ["UX"],
  },
  {
    id: "task-11",
    title: "Checkout flow hand-off pack",
    description: "Annotated Figma hand-off with redlines and component specs.",
    status: "Completed",
    priority: "High",
    project: "App Redesign",
    assignee: DANIEL,
    dueDate: "2026-05-27",
    createdAt: "2026-05-08",
  },
  {
    id: "task-12",
    title: "Navigation shell components",
    description: "Top nav and sidebar shell built in code for dev hand-off.",
    status: "In Review",
    priority: "Medium",
    project: "Dashboard UI",
    assignee: JON,
    dueDate: "2026-06-12",
    createdAt: "2026-05-18",
  },
  {
    id: "task-13",
    title: "Story templates moodboard",
    description: "Visual inspiration board with at least 20 references.",
    status: "To Do",
    priority: "Low",
    project: "Social Templates",
    assignee: ADA,
    dueDate: "2026-06-14",
    createdAt: "2026-05-18",
    tags: ["Moodboard"],
  },
  {
    id: "task-14",
    title: "Explore onboarding flow variants",
    description: "Three onboarding directions: carousel, checklist, and modal.",
    status: "To Do",
    priority: "Medium",
    project: "App Redesign",
    dueDate: "2026-06-20",
    createdAt: "2026-05-20",
    tags: ["UX", "Mobile"],
  },
  {
    id: "task-15",
    title: "Collect references for pricing page",
    description: "Curate 15–20 SaaS pricing page references into a Figma board.",
    status: "To Do",
    priority: "Low",
    project: "Landing Page",
    assignee: SARA,
    dueDate: "2026-06-18",
    createdAt: "2026-05-21",
  },
]
