import type {
  AnalyticsData,
  ClientDataPoint,
  ProjectPerformanceRow,
  StatusDataPoint,
  TimeRange,
  WorkloadDataPoint,
} from "./types"

// ── snapshot data (same across all time ranges) ───────────────────────────────

const STATUS_BREAKDOWN: StatusDataPoint[] = [
  { status: "Discovery", count: 1, colorKey: "discovery" },
  { status: "Design",    count: 3, colorKey: "design"    },
  { status: "Review",    count: 1, colorKey: "review"    },
  { status: "Handoff",   count: 1, colorKey: "handoff"   },
]

const WORKLOAD: WorkloadDataPoint[] = [
  { member: "Daniel", tasks: 8, colorKey: "daniel" },
  { member: "Maya",   tasks: 6, colorKey: "maya"   },
  { member: "Jon",    tasks: 5, colorKey: "jon"     },
  { member: "Ada",    tasks: 4, colorKey: "ada"     },
  { member: "Sara",   tasks: 2, colorKey: "sara"    },
]

const CLIENT_BREAKDOWN: ClientDataPoint[] = [
  { client: "Wix",     revenue: 4800, colorKey: "wix"     },
  { client: "Slack",   revenue: 6200, colorKey: "slack"   },
  { client: "Zoom",    revenue: 3400, colorKey: "zoom"    },
  { client: "Monday",  revenue: 5100, colorKey: "monday"  },
  { client: "Fiverr",  revenue: 2800, colorKey: "fiverr"  },
  { client: "Meta",    revenue: 1900, colorKey: "meta"    },
]

const PROJECT_ROWS: ProjectPerformanceRow[] = [
  {
    id: "wix-app-redesign",
    name: "App Redesign",
    subtitle: "Mobile + Web",
    client: "Wix",
    clientLogo: "/logos/wix.png",
    status: "Design",
    tasksDone: 8,
    tasksTotal: 14,
    overdueTasks: 0,
    revenue: 4800,
    lastActivity: "1 day ago",
  },
  {
    id: "slack-dashboard-ui",
    name: "Dashboard UI",
    subtitle: "Analytics module",
    client: "Slack",
    clientLogo: "/logos/slack.png",
    status: "Handoff",
    tasksDone: 18,
    tasksTotal: 18,
    overdueTasks: 2,
    revenue: 6200,
    lastActivity: "4 days ago",
  },
  {
    id: "zoom-landing-page",
    name: "Landing Page",
    subtitle: "Pricing + Hero",
    client: "Zoom",
    clientLogo: "/logos/zoom.png",
    status: "Design",
    tasksDone: 6,
    tasksTotal: 15,
    overdueTasks: 1,
    revenue: 3400,
    lastActivity: "2 days ago",
  },
  {
    id: "monday-brand-identity",
    name: "Brand Identity",
    subtitle: "Logo system",
    client: "Monday",
    clientLogo: "/logos/monday.png",
    status: "Review",
    tasksDone: 12,
    tasksTotal: 12,
    overdueTasks: 0,
    revenue: 5100,
    lastActivity: "1 day ago",
  },
  {
    id: "fiverr-marketing-kit",
    name: "Marketing Kit",
    subtitle: "Social + Email",
    client: "Fiverr",
    clientLogo: "/logos/fiverr.png",
    status: "Design",
    tasksDone: 4,
    tasksTotal: 10,
    overdueTasks: 0,
    revenue: 2800,
    lastActivity: "3 days ago",
  },
  {
    id: "meta-social-templates",
    name: "Social Templates",
    subtitle: "Story + Feed",
    client: "Meta",
    clientLogo: "/logos/meta.png",
    status: "Discovery",
    tasksDone: 2,
    tasksTotal: 8,
    overdueTasks: 0,
    revenue: 1900,
    lastActivity: "5 days ago",
  },
]

// ── analytics data keyed by time range ───────────────────────────────────────

export const analyticsData: Record<TimeRange, AnalyticsData> = {
  "7d": {
    kpis: [
      { label: "Monthly Revenue",    value: "$3,580",  delta: "+8% vs prev 7d",   deltaPositive: true  },
      { label: "Active Projects",    value: "6",       delta: "no change",         deltaPositive: true  },
      { label: "Completed Tasks",    value: "19",      delta: "+18% vs prev 7d",   deltaPositive: true  },
      { label: "Overdue Tasks",      value: "3",       delta: "−1 vs prev 7d",     deltaPositive: false },
      { label: "Avg Tasks / Member", value: "3.8",     delta: "+5% vs prev 7d",    deltaPositive: true  },
    ],
    revenue: [
      { period: "Sun", revenue: 380  },
      { period: "Mon", revenue: 510  },
      { period: "Tue", revenue: 480  },
      { period: "Wed", revenue: 620  },
      { period: "Thu", revenue: 590  },
      { period: "Fri", revenue: 720  },
      { period: "Sat", revenue: 280  },
    ],
    tasks: [
      { period: "Sun", completed: 2 },
      { period: "Mon", completed: 3 },
      { period: "Tue", completed: 2 },
      { period: "Wed", completed: 4 },
      { period: "Thu", completed: 3 },
      { period: "Fri", completed: 4 },
      { period: "Sat", completed: 1 },
    ],
    statusBreakdown: STATUS_BREAKDOWN,
    workload:        WORKLOAD,
    clientBreakdown: CLIENT_BREAKDOWN,
    projectRows:     PROJECT_ROWS,
  },

  "30d": {
    kpis: [
      { label: "Monthly Revenue",    value: "$13,700", delta: "+11% vs prev 30d",  deltaPositive: true  },
      { label: "Active Projects",    value: "6",       delta: "no change",          deltaPositive: true  },
      { label: "Completed Tasks",    value: "35",      delta: "+18% vs prev 30d",   deltaPositive: true  },
      { label: "Overdue Tasks",      value: "3",       delta: "−1 vs prev 30d",     deltaPositive: false },
      { label: "Avg Tasks / Member", value: "7.0",     delta: "+9% vs prev 30d",    deltaPositive: true  },
    ],
    revenue: [
      { period: "Wk 1", revenue: 2800 },
      { period: "Wk 2", revenue: 3200 },
      { period: "Wk 3", revenue: 3600 },
      { period: "Wk 4", revenue: 4100 },
    ],
    tasks: [
      { period: "Wk 1", completed: 7  },
      { period: "Wk 2", completed: 8  },
      { period: "Wk 3", completed: 9  },
      { period: "Wk 4", completed: 11 },
    ],
    statusBreakdown: STATUS_BREAKDOWN,
    workload:        WORKLOAD,
    clientBreakdown: CLIENT_BREAKDOWN,
    projectRows:     PROJECT_ROWS,
  },

  "3m": {
    kpis: [
      { label: "Monthly Revenue",    value: "$15,200", delta: "+12% vs prev 3m",   deltaPositive: true  },
      { label: "Active Projects",    value: "6",       delta: "+2 vs prev 3m",     deltaPositive: true  },
      { label: "Completed Tasks",    value: "54",      delta: "+20% vs prev 3m",   deltaPositive: true  },
      { label: "Overdue Tasks",      value: "3",       delta: "−1 vs prev 3m",     deltaPositive: false },
      { label: "Avg Tasks / Member", value: "10.8",    delta: "+10% vs prev 3m",   deltaPositive: true  },
    ],
    revenue: [
      { period: "Feb", revenue: 12200 },
      { period: "Mar", revenue: 13800 },
      { period: "Apr", revenue: 15200 },
    ],
    tasks: [
      { period: "Feb", completed: 16 },
      { period: "Mar", completed: 18 },
      { period: "Apr", completed: 20 },
    ],
    statusBreakdown: STATUS_BREAKDOWN,
    workload:        WORKLOAD,
    clientBreakdown: CLIENT_BREAKDOWN,
    projectRows:     PROJECT_ROWS,
  },

  "6m": {
    kpis: [
      { label: "Monthly Revenue",    value: "$18,400", delta: "+14% vs prev 6m",   deltaPositive: true  },
      { label: "Active Projects",    value: "6",       delta: "+2 vs prev 6m",     deltaPositive: true  },
      { label: "Completed Tasks",    value: "87",      delta: "+23% vs prev 6m",   deltaPositive: true  },
      { label: "Overdue Tasks",      value: "3",       delta: "−1 vs prev 6m",     deltaPositive: false },
      { label: "Avg Tasks / Member", value: "17.4",    delta: "+4% vs prev 6m",    deltaPositive: true  },
    ],
    revenue: [
      { period: "Nov", revenue: 10400 },
      { period: "Dec", revenue: 11800 },
      { period: "Jan", revenue: 13200 },
      { period: "Feb", revenue: 14600 },
      { period: "Mar", revenue: 16100 },
      { period: "Apr", revenue: 18400 },
    ],
    tasks: [
      { period: "Nov", completed: 10 },
      { period: "Dec", completed: 12 },
      { period: "Jan", completed: 14 },
      { period: "Feb", completed: 16 },
      { period: "Mar", completed: 18 },
      { period: "Apr", completed: 17 },
    ],
    statusBreakdown: STATUS_BREAKDOWN,
    workload:        WORKLOAD,
    clientBreakdown: CLIENT_BREAKDOWN,
    projectRows:     PROJECT_ROWS,
  },

  "12m": {
    kpis: [
      { label: "Monthly Revenue",    value: "$22,800", delta: "+18% vs prev 12m",  deltaPositive: true  },
      { label: "Active Projects",    value: "6",       delta: "+2 vs prev 12m",    deltaPositive: true  },
      { label: "Completed Tasks",    value: "156",     delta: "+31% vs prev 12m",  deltaPositive: true  },
      { label: "Overdue Tasks",      value: "3",       delta: "−2 vs prev 12m",    deltaPositive: false },
      { label: "Avg Tasks / Member", value: "31.2",    delta: "+12% vs prev 12m",  deltaPositive: true  },
    ],
    revenue: [
      { period: "May", revenue: 7200  },
      { period: "Jun", revenue: 8100  },
      { period: "Jul", revenue: 8800  },
      { period: "Aug", revenue: 9600  },
      { period: "Sep", revenue: 10400 },
      { period: "Oct", revenue: 11800 },
      { period: "Nov", revenue: 12600 },
      { period: "Dec", revenue: 13800 },
      { period: "Jan", revenue: 15200 },
      { period: "Feb", revenue: 16600 },
      { period: "Mar", revenue: 18400 },
      { period: "Apr", revenue: 22800 },
    ],
    tasks: [
      { period: "May", completed: 8  },
      { period: "Jun", completed: 9  },
      { period: "Jul", completed: 10 },
      { period: "Aug", completed: 11 },
      { period: "Sep", completed: 12 },
      { period: "Oct", completed: 13 },
      { period: "Nov", completed: 14 },
      { period: "Dec", completed: 15 },
      { period: "Jan", completed: 16 },
      { period: "Feb", completed: 17 },
      { period: "Mar", completed: 18 },
      { period: "Apr", completed: 13 },
    ],
    statusBreakdown: STATUS_BREAKDOWN,
    workload:        WORKLOAD,
    clientBreakdown: CLIENT_BREAKDOWN,
    projectRows:     PROJECT_ROWS,
  },
}
